#!/usr/bin/env bash

if [[ -z "$(command -v brew 2> /dev/null)" ]]; then
  echo "brew is not installed"
  exit 1
fi

PACKAGES="fzf the_silver_searcher"
LINUX_PACKAGES="xclip"

[[ "$(uname)" == "Linux" ]] && PACKAGES="$PACKAGES $LINUX_PACKAGES"

brew install $PACKAGES
