#!/usr/bin/env bash

# Install git if it does not exist
if [[ -z "$(command -v git 2> /dev/null)" ]]; then
  if [[ -z "$(command -v brew 2> /dev/null)" ]]; then
    echo "brew is not installed"
    exit 1
  else
    brew install git
  fi
fi

# Symlink
ORIGIN=$HOME/.files/git/gitignore
TARGET=$HOME/.gitignore

mkdir -p "$(dirname "$TARGET")"
rm -rf "$TARGET"
ln -sf "$ORIGIN" "$TARGET"

# Additional git configs
git config --global user.name "boggs"
git config --global user.email "hello@boggs.xyz"
git config --global core.excludesfile $HOME/.gitignore
