language: generic
arch:
  - amd64
env:
  global:
    - DOCKER_USERNAME=bxggs
    - DEFAULT_DOCKER_TAG=latest
services:
  - docker
before_script:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      export DOCKER_TAG=$DEFAULT_DOCKER_TAG;
    else
      export DOCKER_TAG=$(echo "$TRAVIS_BRANCH" | awk '{ gsub("/", "-"); print $0 }');
    fi
  - docker build -t "$DOCKER_REPOSITORY:$DOCKER_TAG" .
deploy:
  provider: script
  script: bash -c 'echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push "$DOCKER_REPOSITORY:$DOCKER_TAG"'
  on:
    all_branches: true
