#!/usr/bin/env bash

# Install ruby if it does not exist
if [[ -z "$(command -v gem 2> /dev/null)" ]]; then
  if [[ -z "$(command -v brew 2> /dev/null)" ]]; then
    echo "brew is not installed"
    exit 1
  else
    brew install ruby
  fi
fi

# Install tmuxinator if it does not exist
if [[ -z "$(gem list | grep tmuxinator)" ]]; then
  gem install tmuxinator --no-doc --no-ri
fi

# Symlink
ORIGIN=$HOME/.files/tmuxinator
TARGET=$HOME/.tmuxinator

mkdir -p "$(dirname "$TARGET")"
rm -rf "$TARGET"
ln -sf "$ORIGIN" "$TARGET"
