#!/usr/bin/env bash

if [[ ! "$(which zsh)" ]]; then
  if [[ "$(which brew)" ]]; then
    brew install neovim
  elif [[ "$(which apt-get)" ]]; then
    sudo apt-get install -y neovim
  fi
fi

$(dirname "$0")/symlink_nvim

curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

nvim +PlugInstall +qall
