#!/usr/bin/env bash

# # Install git if it does not exist
# if [[ ! "$(which nvim)" ]]; then
#   if [[ "$(which brew)" ]]; then
#     brew install nvim
#   elif [[ "$(which apt)" ]]; then
#     sudo apt install -y neovim
#   fi
# fi

# # Install vim-plug
# curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
#
# # Install plugins and quit
# nvim +PlugInstall +qall
