#!/usr/bin/env bash

if [[ ! "$(which zsh)" ]]; then
  if [[ "$(which brew)" ]]; then
    brew install vim
  elif [[ "$(which apt-get)" ]]; then
    sudo apt-get install -y vim
  fi
fi

../symlink_vim

curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
