format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$time\
${custom.ssh}
$character"""

[directory]
format = "[](fg:purple)[$path](bg:purple fg:black bold)[](fg:purple) "

[git_branch]
format = "$branch"

[git_status]
format = "($conflicted$untracked$modified$staged$renamed$deleted) "
conflicted = "*"
untracked = "*"
modified = "*"
staged = "*"
renamed = "*"
deleted = "*"

[python]
format = "(python-$version( $virtualenv)) "
symbol = ""
version_format = "$raw"

[nodejs]
format = "(node-$version) "
symbol = ""
version_format = "$raw"

[time]
format = "$time "
disabled = false

[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "[\\$](blue)"

[custom.ssh]
format = "SSH "
when = """ test ! -z "$SSH_CLIENT" """
