format = """
$directory\
$git_branch\
$git_status\
$python\
$nodejs\
$time\
$cmd_duration\
${custom.ssh}\
${custom.docker}
$character"""

[directory]
format = "[](fg:purple)[$path](bg:purple fg:black bold)[](fg:purple) "

[git_branch]
format = "$branch"

[git_status]
format = "($conflicted$untracked$modified$staged$renamed$deleted) "
conflicted = "*"
untracked = "*"
modified = "*"
staged = "*"
renamed = "*"
deleted = "*"

[python]
format = "(python-$version( $virtualenv)) "
symbol = ""
version_format = "$raw"

[nodejs]
format = "(node-$version) "
symbol = ""
version_format = "$raw"

[time]
format = "$time "
disabled = false

[cmd_duration]
format = "$duration "

[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "[\\$](blue)"

[custom.ssh]
format = "SSH "
when = """ test ! -z "$SSH_CLIENT" """

[custom.docker]
format = "Docker "
when = """ test ! -z "$IN_DOCKER" """
