#!/usr/bin/env bash

# battery
# @b_ggs // github.com/b-ggs/macos-sysinfo-scripts
# Returns Mac's current battery level, state (charging, discharging),
# and time remaining

# TODO: Check if battery is disconnected or unavailable

details=$(pmset -g batt | grep %)

field_separator="[)]|(; )|(remaining)|(present:)"

present=$(echo "$details" | awk -F "$field_separator" '{ print $6 }' | sed 's/^[[:space:]]*//g')
percent=$(echo "$details" | awk -F "$field_separator" '{ print $2 }' | sed 's/^[[:space:]]*//g')
state=$(echo "$details" | awk -F "$field_separator" '{ print $3 }')
remaining=$(echo "$details" | awk -F "$field_separator" '{ print $4 }' | sed 's/(//g')

echo $present
echo $percent
echo $state
echo $remaining
