#!/usr/bin/env bash

# brightness
# @b_ggs // github.com/b-ggs/macos-sysinfo-scripts
# Returns main display's brightness percentage

backlight=$(ioreg -c AppleBacklightDisplay -r -d 1 | grep -o '"brightness"={"max"=[0-9]*,"min"=[0-9]*,"value"=[0-9]*}')

field_separator='("max"=)|(,"min"=)|(,"value"=)|(})'

max=$(echo "$backlight" | awk -F "$field_separator" '{ print $2 }')
min=$(echo "$backlight" | awk -F "$field_separator" '{ print $3 }')
value=$(echo "$backlight" | awk -F "$field_separator" '{ print $4 }')

percent=$(awk "BEGIN { print int($value / ($max - $min) * 100) }")

echo "$percent%"
