#!/usr/bin/env bash

# spotify_status
# @b_ggs // github.com/b-ggs/macos-sysinfo-scripts
# Returns current track's title, artist, and state (playing, paused) on Spotify

if [[ ! $(pgrep -x Spotify) ]]; then
  echo '{ "state": "not running" }'
  exit 1
fi

player_state=$(osascript -e 'tell application "Spotify" to player state as string')
title=$(osascript -e 'tell application "Spotify" to name of current track as string')
artist=$(osascript -e 'tell application "Spotify" to artist of current track as string')
album=$(osascript -e 'tell application "Spotify" to album of current track as string')

json='{ '
json="${json}\"state\": \"$player_state\", "
json="${json}\"title\": \"$title\", "
json="${json}\"artist\": \"$artist\", "
json="${json}\"album\": \"$album\""
json="${json} }"

echo $json
