onboarding = false

[keys]
prefix = "ctrl+s"
split_vertical = "prefix+\\"
split_horizontal = "prefix+minus"
new_workspace = "prefix+shift+c"
previous_workspace = "prefix+shift+p"
next_workspace = "prefix+shift+n"

[ui]
agent_panel_sort = "spaces"
prompt_new_tab_name = false

# https://github.com/iurysza/herdr-pane-layouts

[[keys.command]]
key = "prefix+space"
type = "plugin_action"
command = "layouts.cycle"
description = "cycle pane layouts"

[[keys.command]]
key = "prefix+left"
type = "plugin_action"
command = "layouts.resize-left"
description = "resize pane left"

[[keys.command]]
key = "prefix+right"
type = "plugin_action"
command = "layouts.resize-right"
description = "resize pane right"

[[keys.command]]
key = "prefix+down"
type = "plugin_action"
command = "layouts.resize-down"
description = "resize pane down"

[[keys.command]]
key = "prefix+up"
type = "plugin_action"
command = "layouts.resize-up"
description = "resize pane up"
