# vim: set ft=ruby:

brew "aria2"
brew "bat"
brew "boxes"
brew "btop"
brew "cmake"
brew "curl"
brew "eza"
brew "fnm"
brew "fzf"
brew "gemini-cli"
brew "git"
brew "gh"
brew "go"
brew "hellwal"
brew "herdr"
brew "htop"
brew "just"
brew "keychain"
brew "neovim"
brew "parallel"
brew "pngcrush"
brew "poetry"
brew "progress"
brew "ripgrep"
brew "starship"
brew "stow"
brew "tmux"
brew "tmuxp"
brew "tldr"
brew "tree"
brew "tree-sitter-cli"
brew "um"
brew "uv"
brew "universal-ctags"
brew "watch"
brew "wget"

# Browsers
cask "brave-browser"
cask "ungoogled-chromium"
cask "firefox"
cask "google-chrome"
cask "helium-browser"

cask "1password"
cask "1password-cli"
cask "android-platform-tools"
cask "claude-code@latest"
cask "codex"
cask "dbeaver-community"
cask "discord"
cask "hammerspoon"
cask "karabiner-elements"
cask "keepingyouawake"
cask "keka"
cask "kitty"
cask "notion"
cask "obs"
cask "obsidian"
cask "orbstack"
cask "raycast"
cask "scroll-reverser"
cask "slack"
cask "spotify"
cask "swiftbar"
cask "tailscale-app"
cask "telegram"
cask "transmission"
cask "visual-studio-code"
cask "vlc"
cask "vnc-viewer"

tap "anomalyco/tap", trust: true
brew "anomalyco/tap/opencode", trust: true

tap "heroku/brew", trust: true
brew "heroku/brew/heroku", trust: true

tap "zuisong/tap", trust: true
brew "zuisong/tap/rs-fortune", trust: true

tap "psviderski/tap", trust: true
cask "psviderski/tap/docker-pussh", trust: true

tap "Sanyam-G/switch", trust: true
cask "Sanyam-G/switch/switch", trust: true
