#!/usr/bin/env bash

PACKAGES="curl git nvim vim zsh tmux gpg"
BREW_PACKAGES="fzf the_silver_searcher"
APT_PACKAGES="silversearcher-ag"

if [[ "$(which brew)" ]]; then
  brew install $PACKAGES $BREW_PACKAGES
else if [[ "$(which apt-get)" ]]; then
  sudo apt-get install -y $PACKAGES $APT_PACKAGES

  # Install fzf manually because it's not available on apt-get
  if [[ ! -d "~/.fzf" ]]; then
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
  fi
fi

