#!/usr/bin/env bash

# Install tmux if it does not exist
if [[ -z "$(command -v tmux 2> /dev/null)" ]]; then
  if [[ -z "$(command -v brew 2> /dev/null)" ]]; then
    echo "brew is not installed"
    exit 1
  else
    brew install tmux
  fi
fi

 Symlink
ORIGIN=$HOME/.files/tmux/tmux.conf
TARGET=$HOME/.tmux.conf

mkdir -p "$(dirname "$TARGET")"
rm -rf "$TARGET"
ln -sf "$ORIGIN" "$TARGET"
