#!/usr/bin/env bash

# Install tmux if it does not exist
if [[ ! "$(which tmux)" ]]; then
  if [[ "$(which brew)" ]]; then
    brew install tmux
  elif [[ "$(which apt)" ]]; then
    sudo apt install -y tmux
  fi
fi

# Symlink
ORIGIN=$HOME/.dotfiles/tmux/tmux.conf
TARGET=$HOME/.tmux.conf

mkdir -p "$(dirname "$TARGET")"
rm -rf "$TARGET"
ln -sf "$ORIGIN" "$TARGET"
