#!/usr/bin/env bash

if [[ -z "$(command -v zsh 2> /dev/null)" ]]; then
  if [[ -z "$(command -v brew 2> /dev/null)" ]]; then
    echo "brew is not installed"
    exit 1
  else
    brew install zsh
  fi
fi

zsh_path="$(command -v zsh)"

# Install zgen if it does not exist

zgen_path="$HOME/.zgen"
if [[ ! -e "$zgen_path" ]]; then
  git clone https://github.com/tarjoilija/zgen.git "$zgen_path"
fi

# Symlink

origin_paths="$(ls -d -1 $(dirname $(realpath "$0"))/*.zsh)"
target_dir="$HOME/.zsh"

mkdir -p "$target_dir"

for origin_path in $origin_paths; do
  basename="$(basename $origin_path)"
  target_path="$target_dir/$basename"

  rm -f "$target_path"
  ln -sf "$origin_path" "$target_path"
done

ln -sf "$target_dir/init.zsh" "$HOME/.zshrc"

# Change default shell to zsh
echo "Changing default shell... SIGKILL to stop"

if [[ "$PREFIX" == "/data/data/com.termux/files/usr" ]] && [[ "$(uname -o)" != "Android" ]]; then
  # Special case for Termux
  chsh -s "zsh"
else
  if [[ ! "$(cat /etc/shells | grep $zsh_path)" ]]; then
    sudo sh -c "echo ${zsh_path} >> /etc/shells"
  fi
  chsh -s "$zsh_path"
fi
