format = """
$directory\
$git_branch\
$python\
$time
$character"""

[directory]
format = "[$path](red) "

[git_branch]
format = "$branch "

[python]
format = "$version( $virtualenv) "
symbol = ""
version_format = "$raw"

[time]
format = "$time"
disabled = false

[character]
success_symbol = "\\$"
error_symbol = "[\\$](red)"
vicmd_symbol = "[\\$](blue)"
