#!/usr/bin/env bash

# Install git if it does not exist
if [[ ! "$(which nvim)" ]]; then
  if [[ "$(which brew)" ]]; then
    brew install nvim
  elif [[ "$(which apt)" ]]; then
    sudo apt install -y neovim
  fi
fi

# Symlink
ORIGIN=$HOME/.files/neovim/init.vim
TARGET=$HOME/.config/nvim/init.vim

mkdir -p "$(dirname "$TARGET")"
rm -rf "$TARGET"
ln -sf "$ORIGIN" "$TARGET"

# Install vim-plug
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Install plugins and quit
nvim +PlugInstall +qall
