name: docker-linux

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile:
          - Dockerfile.arch
          - Dockerfile.debian
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          docker build -t dotfiles -f "${{ matrix.dockerfile }}" .
      - name: Show package versions
        run: |
          docker \
            run \
            --rm \
            dotfiles \
            zsh -c "nvim --version \
              && zsh --version \
              && tmux -V \
              && rg --version \
              && git --version \
              && \$HOME/.local/share/fnm/fnm exec --using=22 node --version \
              && \$HOME/.local/share/fnm/fnm exec --using=22 npm list --location=global \
            "
