name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Stylua
        run: |
          npx @johnnymorganz/stylua-bin -c -g nvim/.config/nvim/**/*.lua
